name: Create Zip File
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get Mod Version Number
      id: mod_version
      uses:  ashley-taylor/read-json-property-action@v1.2
      with:
        path: ModConfig.json
        property: ModVersion
    - name: echo ModVersion
      run: echo ${{ steps.mod_version.outputs.value }}
      env:
        release_mod_version: ${{ steps.mod_version.outputs.value }}
    - name: Get Mod ID
      id: mod_id
      uses:  ashley-taylor/read-json-property-action@v1.2
      with:
        path: ModConfig.json
        property: ModId
    - name: echo ModId
      run: echo ${{ steps.mod_id.outputs.value }}}
      env:
        release_mod_id: ${{ steps.mod_id.outputs.value }}
      #build zip
    - name: Generate Name
      id: zip_name
      uses: aymen3009/slugifyAction@v1.1.1
      with:
        # string input
        string: steps.mod_id.outputs.value # default is Hello World
        suffix: steps.mod_version.outputs.value
    - name: echo Zip Name
      run: echo ${{ steps.zip_name.outputs.value }}}
    - name: Generate File Name
      id: zip_filename
      uses: aymen3009/slugifyAction@v1.1.1
      with:
        # string input
        string: steps.zip_name.outputs.value # default is Hello World
        suffix: ".zip"
        slugify: false
    - name: Generate ZIP
      uses: byteever/action-build-zip@master
      with:
        filename: steps.zip_filename.outputs.value
