name: Create Zip File
on: 
  workflow_dispatch:
jobs:
  read_mod_config:
    runs-on: ubuntu-latest
    steps:
    - name: Get Mod Version Number
      id: mod_version
      uses:  ashley-taylor/read-json-property-action@v1.2
      with:
        path: ././ModConfig.json
        property: ModVersion
    - name: echo ModVersion
      run: echo ${{ steps.mod_version.outputs.value }}
      env:
        release_mod_version: ${{ steps.mod_version.outputs.value }}
    - name: Get Mod ID
      id: mod_id
      uses:  ashley-taylor/read-json-property-action@v1.2
      with:
        path: ModConfig.json
        property: ././ModId
    - name: echo ModId
      run: echo ${{ steps.mod_id.outputs.value }}}
      env:
        release_mod_id: ${{ steps.mod_id.outputs.value }}
    - name: NameZip
      id: release-name
      # You may pin to the exact commit or the version.
      # uses: michpohl/action-concatenate-strings@595fbe6538a309ac7f4c6afbc5c11b9d6e724ef8
      uses: michpohl/action-concatenate-strings@v1.0.1
      with:
        # Your first string
        first: release_mod_id
        # Your second string
        second: release_mod_version
        # A string to put between the first and second provided strings
        separator: '-' 
        # The name of the output env var
        output-var-name: thisZIP
    - name: echo NameZip
      run: echo ${{ steps.release-name.outputs.value }}}
              
