name: action-build-zip
  # You may pin to the exact commit or the version.
  # uses: byteever/action-build-zip@23d77e1778849e35de1b4e9dbb16d4b64a4714e6
  uses: byteever/action-build-zip@1
  with:
    # See byteever/action-zip README.md for more info
    filename: # optional
          
