name: Release Name Generator
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  getVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: getVersionString
      # You may pin to the exact commit or the version.
      # uses: Muchaszewski/read-json-action@25572fc3515f2520c4d18072d815c368e2c5d323
      uses: Muchaszewski/read-json-action@1.0.0
      with:
        # Path to the json file
        path: ModConfig.json # optional, default is package.json
        # Property or an array to read eg: "[name, version, repository.url]" or "name"
        properties: "[ModID, ModVersion]"
    - name: echo Version
      run: echo ${{ steps.getVersionString.outputs.array }}}
