# Script to build and publish a Reloaded Mod.
# by Sewer56

# Produces: 
#   - Build to Upload to GameBanana
#   - Build to Upload to GitHub
#   - Build to Upload to NuGet
#   - Changelog

# When pushing a tag
#   - Upload to GitHub Releases
#   - Upload to Reloaded NuGet Repository (if GitHub Secret RELOADED_NUGET_KEY is specified) 

name: Build and Publish Reloaded Mod

on:
  workflow_dispatch:

env: 
  RELOADEDIIMODS: .
  PUBLISH_COMMON_PATH: ./Publish/ToUpload/

  PUBLISH_GAMEBANANA_PATH: ./Publish/ToUpload/GameBanana
  PUBLISH_GITHUB_PATH: ./Publish/ToUpload/Generic
  PUBLISH_NUGET_PATH: ./Publish/ToUpload/NuGet
  
  PUBLISH_CHANGELOG_PATH: ./Publish/Changelog.md
  PUBLISH_PATH: ./Publish

  # Default value is official Reloaded package server.  
  NUGET_URL: http://packages.sewer56.moe:5000/v3/index.json
  
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}
  PROJECT_DIR: .

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
        
    - name: Setup .NET Core SDK (5.0)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core SDK (7.0)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: ${{ env.PROJECT_DIR }}/Publish.ps1

#    - name: Copy Build
#      run: Copy-Item -Force -Path "${{ env.PUBLISH_CHANGELOG_PATH }}/Publish/*" -Destination "./Publish" -Recurse

    - name: Upload GitHub Release Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: GitHub Release
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ${{ env.PUBLISH_GITHUB_PATH }}/*